title: Steganography Tutorial
description: Learn how to hide messages in images using Python
baseurl: "https://github.com/Apepi/quaggaconcepts.github.io"  # Replace with your repo name
url: "https://github.com/Apepi"  # Replace with your GitHub username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
