title: Steganography Tutorial
description: Learn how to hide messages in images using Python
baseurl: "/quaggaconcepts.github.io"  # Replace with your repo name
url: "quaggaconcepts.github.io"  # Replace with your GitHub username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
