title: Steganography Tutorial
description: Learn how to hide messages in images using Python
url: "https://quaggaconcepts.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
